### ISSUE TITLE
Confirm TinyNode functionality with current RERUM

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TinyNode#20]

**Comment by cubap** [comment]
update is wonky (expected) and delete is not working (expected) but all the rest are doing fine

**Comment by thehabes** [comment]
@cubap I've looked at #22, that is quite a new package!

A major part of testing TinyNode will be ensuring the headers are throughput from v1-node.  I would love if you could test this tiny-node and that v1-node at the same time, and also think about [rerum_server_nodejs/issues/53 ](https://github.com/CenterForDigitalHumanities/rerum_server_nodejs/issues/53) as you go through.  Maybe even write tests for tiny-node that confirm the header throuput, it is super important so we avoid the "Content length mismatch" and other weird errors that crash the apps.
