### ISSUE TITLE
Location isn't found on `create` because of capitalization

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TinyNode#6]

**Comment by cubap** [comment]
Access-Control-Expose-Headers

**Comment by cubap** [comment]
Probably just waiting on https://github.com/CenterForDigitalHumanities/rerum_server_nodejs/issues/3

**Comment by thehabes** [comment]
It is all lined up now.  Use capitalized **L**ocation, I am writing in routes like `res.set("Location", obj["@id"])`.  fetch API will respect the capitalization.  Other HTTPRequest APIs may not.

**Comment by cubap** [comment]
Just a note. This isn't about "respecting" capitalization, but "normalization". Intermediate servers, it turns out, may or may not keep case, so some libraries like `got` normalize by lowercasing. This can be changed in the configuration or switched to Title Casing, if we decide.
