### ISSUE TITLE
RESTful Responses for unhandled methods on published routes

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TinyNode#72]
Double check the HTTP response codes sent out for the various HTTP error scenarios.  There are instances of it not being quite right.

For example, if you do a `PUT` request to `/query` you get a `404` response instead of a `405`

**Comment by cubap** [comment]
hmmm...
This is still technically RESTful. The route+method is not in the application, so the request is not found on the server: 404. In other places we have put an `.all()` at the end of a defined route that offers a 405. Is this the suggestion?

**Comment by cubap** [comment]
PR is in. I haven't surveyed all the possible failures, but the example is handled across all routes.
